services:
  mongodb:
    image: mongo:latest
    container_name: mongotc
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mongotc
    volumes:
      - C:/app-tacontigo/mongodb-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
