services:
  mongodb:
    image: mongo:latest
    container_name: mongotc
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mongotc
    volumes:
      - C:/app-tacontigo/mongodb-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: tacontigo-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      JAVA_OPTS_APPEND: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
      MONGO_CONNECTION_STRING: "mongodb://admin:secret@mongotc:27017/mongotc"
      MONGO_DB_NAME: "mongotc"
